### ISSUE TITLE
Failed to handle method call

### ISSUE THREAD

**Issue by 1encore** [flyyyxxxy/dgis_flutter#2]
Getting this error with example from [pub.dev](https://pub.dev/packages/dgis_flutter/example)

```
E/MethodChannel#flutter/platform_views(31148): Failed to handle method call
E/MethodChannel#flutter/platform_views(31148): ru.dgis.sdk.NativeException: Reinitialization is not allowed.
E/MethodChannel#flutter/platform_views(31148): 	at ru.dgis.sdk.Global.$createContext(Native Method)
E/MethodChannel#flutter/platform_views(31148): 	at ru.dgis.sdk.DGis.initialize(DGis.kt:36)
E/MethodChannel#flutter/platform_views(31148): 	at ru.dgis.sdk.DGis.initialize$default(DGis.kt:28)
E/MethodChannel#flutter/platform_views(31148): 	at com.example.dgis_flutter.NativeView.<init>(NativeView.kt:38)
E/MethodChannel#flutter/platform_views(31148): 	at com.example.dgis_flutter.NativeViewFactory.create(NativeViewFactory.kt:16)
E/MethodChannel#flutter/platform_views(31148): 	at io.flutter.plugin.platform.PlatformViewsController$1.createForTextureLayer(PlatformViewsController.java:197)
E/MethodChannel#flutter/platform_views(31148): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:122)
E/MethodChannel#flutter/platform_views(31148): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:60)
E/MethodChannel#flutter/platform_views(31148): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/MethodChannel#flutter/platform_views(31148): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#flutter/platform_views(31148): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:319)
E/MethodChannel#flutter/platform_views(31148): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run(lambda)
E/MethodChannel#flutter/platform_views(31148): 	at android.os.Handler.handleCallback(Handler.java:754)
E/MethodChannel#flutter/platform_views(31148): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/MethodChannel#flutter/platform_views(31148): 	at android.os.Looper.loop(Looper.java:163)
E/MethodChannel#flutter/platform_views(31148): 	at android.app.ActivityThread.main(ActivityThread.java:6238)
E/MethodChannel#flutter/platform_views(31148): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter/platform_views(31148): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:933)
E/MethodChannel#flutter/platform_views(31148): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
E/flutter (31148): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: PlatformException(error, Reinitialization is not allowed., null, ru.dgis.sdk.NativeException: Reinitialization is not allowed.
E/flutter (31148): 	at ru.dgis.sdk.Global.$createContext(Native Method)
E/flutter (31148): 	at ru.dgis.sdk.DGis.initialize(DGis.kt:36)
E/flutter (31148): 	at ru.dgis.sdk.DGis.initialize$default(DGis.kt:28)
E/flutter (31148): 	at com.example.dgis_flutter.NativeView.<init>(NativeView.kt:38)
E/flutter (31148): 	at com.example.dgis_flutter.NativeViewFactory.create(NativeViewFactory.kt:16)
E/flutter (31148): 	at io.flutter.plugin.platform.PlatformViewsController$1.createForTextureLayer(PlatformViewsController.java:197)
E/flutter (31148): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:122)
E/flutter (31148): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:60)
E/flutter (31148): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/flutter (31148): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/flutter (31148): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:319)
E/flutter (31148): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run(lambda)
E/flutter (31148): 	at android.os.Handler.handleCallback(Handler.java:754)
E/flutter (31148): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/flutter (31148): 	at android.os.Looper.loop(Looper.java:163)
E/flutter (31148): 	at android.app.ActivityThread.main(ActivityThread.java:6238)
E/flutter (31148): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (31148): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:933)
E/flutter (31148): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
E/flutter (31148): )
E/flutter (31148): #0      StandardMethodCodec.decodeEnvelope
E/flutter (31148): #1      MethodChannel._invokeMethod
E/flutter (31148): <asynchronous suspension>
E/flutter (31148): #2      TextureAndroidViewController._sendCreateMessage
E/flutter (31148): <asynchronous suspension>
E/flutter (31148): #3      AndroidViewController.create
E/flutter (31148): <asynchronous suspension>
E/flutter (31148): #4      TextureAndroidViewController.setSize
E/flutter (31148): <asynchronous suspension>
E/flutter (31148): #5      RenderAndroidView._sizePlatformView
E/flutter (31148): <asynchronous suspension>
E/flutter (31148):
```

flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.0.2, on Microsoft Windows [Version 10.0.19044.1645], locale ru-RU)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default
      components
[√] Android Studio (version 2020.3)
[√] VS Code (version 1.68.1)
[√] Connected device (4 available)
[√] HTTP Host Availability

! Doctor found issues in 1 category.
```

**Comment by flyyyxxxy** [comment]
Hello, you must pass the access keys to the GisMap widget, namely directoryKey and mapKey, which can be obtained by contacting 2gis support
