### ISSUE TITLE
app crashes when setCameraPosition() executed

### ISSUE THREAD

**Issue by 1encore** [flyyyxxxy/dgis_flutter#3]
```
V/BoostFramework( 9460): BoostFramework() : mPerf = com.qualcomm.qti.Performance@931a052
I/art     ( 9460): Do partial code cache collection, code=16KB, data=30KB
I/art     ( 9460): After code cache collection, code=16KB, data=30KB
I/art     ( 9460): Increasing code cache capacity to 128KB
D/NetworkSecurityConfig( 9460): No Network Security Config specified, using platform default
I/PlatformViewsController( 9460): Hosting view in a virtual display for platform view: 0
W/ResourceType( 9460): No package identifier when getting name for resource number 0x00000000
I/art     ( 9460): Background partial concurrent mark sweep GC freed 44486(4MB) AllocSpace objects, 8(160KB) LOS objects, 54% free, 6MB/14MB, paused 1.173ms total 117.537ms
W/Adreno-ES20( 9460): <get_gpu_clk:229>: open failed: errno 13
I/libOpenSLES( 9460): Emulating old channel mask behavior (ignoring positional mask 0x4, using default mask 0x1 based on channel count of 1)
W/AudioTrack( 9460): AUDIO_OUTPUT_FLAG_FAST denied by client; transfer 1, track 22050 Hz, output 48000 Hz
D/AudioTrack( 9460): Client defaulted notificationFrames to 296 for frameCount 890
W/ResourceType( 9460): No package identifier when getting name for resource number 0x00000000
D/AndroidRuntime( 9460): Shutting down VM
E/AndroidRuntime( 9460): FATAL EXCEPTION: main
E/AndroidRuntime( 9460): java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Double
E/AndroidRuntime( 9460): 	at com.example.dgis_flutter.GisMapController$setCameraPosition$1.invoke(GisMapController.kt:40)
E/AndroidRuntime( 9460): 	at com.example.dgis_flutter.GisMapController$setCameraPosition$1.invoke(GisMapController.kt:37)
E/AndroidRuntime( 9460): 	at ru.dgis.sdk.map.MapView$getMapAsync$1.run(MapView.kt:270)
E/AndroidRuntime( 9460): 	at android.os.Handler.handleCallback(Handler.java:754)
E/AndroidRuntime( 9460): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime( 9460): 	at android.os.Looper.loop(Looper.java:163)
E/AndroidRuntime( 9460): 	at android.app.ActivityThread.main(ActivityThread.java:6238)
E/AndroidRuntime( 9460): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 9460): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:933)
E/AndroidRuntime( 9460): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
W/Adreno-EGLSUB( 9460): <DequeueBuffer:726>: dequeue native buffer fail: No such device, buffer=0x0, handle=0x0
W/Adreno-EGL( 9460): <qeglDrvAPI_eglSwapBuffers:3798>: EGL_BAD_SURFACE
W/Adreno-EGLSUB( 9460): <DequeueBuffer:726>: dequeue native buffer fail: No such device, buffer=0x0, handle=0x0
W/Adreno-EGL( 9460): <qeglDrvAPI_eglSwapBuffers:3798>: EGL_BAD_SURFACE
Lost connection to device.
Exited (sigterm)

```

**Comment by flyyyxxxy** [comment]
Исправил , версия 0.0.31
